# ========================
#  Logger
# =======================
logging:
  level:
    root: INFO
    springboot.test: DEBUG
    com.zaxxer.hikari: WARN
    org.hibernate: WARN
    org.flywaydb.core: WARN
    org.apache.catalina: WARN
    org.springframework.boot.devtools: WARN
    springfox.documentation.swagger: ERROR
  pattern:
    console: "%d{YYYY-MM-dd HH:mm:ss} %-5level [%8.15thread] %-120.120(%logger{100}.%method %line) %n%m%n"

server:
  port: 8080
  version: 1.0.0
  name: spring-demo

swagger:
  enable: true

graphql:
  tools:
    schema-location-pattern: "graphql/*.graphql"
  graphiql:
    enabled: true
  servlet:
    enabled: true
    cors-enabled: true
    exception-handlers-enabled: true
  playground:
    enabled: false
  voyager:
    enabled: true

spring:
  main:
    web-application-type: servlet
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: 3600
  # ========================
  #  Query Pageable
  # =======================
  data:
    web:
      pageable:
        default-page-size: 10        # Default page size. (default: 20)
        max-page-size: 2000          # Maximum page size to be accepted. (default: 2000)
        one-indexed-parameters: true # Whether to expose and assume 1-based page number indexes.
        page-parameter: page         # Page index parameter name.
        prefix:                      # General prefix to be prepended to the page number and page size parameters.
        qualifier-delimiter: _       # Delimiter to be used between the qualifier and the actual page number and size properties.
        size-parameter: size         # Page size parameter name.
      sort:
        sort-parameter: sort         # sort parameter name.
  # ========================
  #  Database
  # =======================
  datasource:
    host: localhost
    port: 5432
    database: mydb
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}?useUnicode=true&characterEncoding=utf-8
    username: postgres
    hikari:
      maximum-pool-size: 1000
      minimum-idle: 10
      connection-timeout: 10000
      max-lifetime: 1800000
      idle-timeout: 600000
      auto-commit: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        default_schema: testt
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  # =========================
  #  Flyway
  # ==========================
  flyway:
    baseline-version: 1.0
    enabled: false
  influx:
    host: 60.251.156.215
    port: 8086
    backup-port: 8088
    url: http://${spring.influx.host}:${spring.influx.port}
    database: lwm2m
    user: admin
    password: 1qaz@WSX

