# ========================
#  Logger
# =======================
logging:
  level:
    root: INFO
    com.zaxxer.hikari: WARN
    org.hibernate: WARN
    org.flywaydb.core: WARN
    org.apache.catalina: WARN
  pattern:
    console: "%clr(%d{dd HH:mm:ss.SSS}){cyan} %clr(%-5level) %clr([%8.15thread]){cyan} %clr(%-120.120(%logger{100}.%method %line)){yellow} %n%clr(%m){faint}%n"

server:
  port: 8080
  version: 1.0.0
  name: spring-demo

spring:
  main:
    web-application-type: servlet
  # ========================
  #  Query Pageable
  # =======================
  data:
    web:
      pageable:
        default-page-size: 5         # Default page size. (default: 20)
        max-page-size: 500           # Maximum page size to be accepted. (default: 2000)
        one-indexed-parameters: true # Whether to expose and assume 1-based page number indexes.
        page-parameter: page         # Page index parameter name.
        prefix:                      # General prefix to be prepended to the page number and page size parameters.
        qualifier-delimiter: _       # Delimiter to be used between the qualifier and the actual page number and size properties.
        size-parameter: size         # Page size parameter name.
        sort:
          sort-parameter: id         # Sort parameter name.
  # ========================
  #  Database
  # =======================
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydb?useUnicode=true&characterEncoding=utf-8
    username: postgres
    password: 123456
  jpa:
    database: POSTGRESQL
    show-sql: false
    open-in-view: true
    properties:
      hibernate:
        default_schema: testt
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  # =========================
  #  Flyway
  # ==========================
  flyway:
    baseline-version: 1.0
    enabled: false


