logging:
  level:
    root: INFO
    springboot.test: ${LOGGER_LEVEL:INFO}
server:
  port: ${SERVER_PORT:8080}

spring:
  # ========================
  #  Database
  # =======================
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres-svc}:${POSTGRES_PORT:5678}/${POSTGRES_DB:postgres}?useUnicode=true&characterEncoding=utf-8
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: ${POSTGRES_SCHEMA:public}


