server:
  port: ${SERVER_PORT:8080}

spring:
  # ========================
  #  Database
  # =======================
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?useUnicode=true&characterEncoding=utf-8
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: ${POSTGRES_SCHEMA}


