logging:
  level:
    root: INFO
    springboot.demo: ${LOGGER_LEVEL:INFO}
server:
  port: ${SERVER_PORT:8080}

swagger:
  enable: ${OPEN_API_ENABLE:false}

graphql:
  graphiql:
    enabled: ${GRAPHIQL_ENABLE:false}
  playground:
    enabled: false

spring:
  # ========================
  #  Database
  # =======================
  datasource:
    host: ${POSTGRES_HOST:postgres-svc}
    port: ${POSTGRES_PORT:5678}
    database: ${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: ${POSTGRES_SCHEMA:public}
  influx:
    host: ${INFLUXDB_HOST:influxdb-svc}
    port: ${INFLUXDB_PORT:8086}
    database: ${INFLUXDB_DB}
    user: ${INFLUXDB_USER}
    password: ${INFLUXDB_PASSWORD}


