logging:
  level:
    root: INFO
  pattern:
    console: "%clr(%d{dd HH:mm:ss.SSS}){cyan} %clr(%-5level) %clr([%8.15thread]){cyan} %clr(%-120.120(%logger{100}.%method %line)){yellow} %n%clr(%m){faint}%n"

server:
  port: 8080

spring:
  data:
    web:
      pageable:
        default-page-size: 5         # Default page size. (default: 20)
        max-page-size: 500           # Maximum page size to be accepted. (default: 2000)
        one-indexed-parameters: true # Whether to expose and assume 1-based page number indexes.
        page-parameter: page         # Page index parameter name.
        prefix:                      # General prefix to be prepended to the page number and page size parameters.
        qualifier-delimiter: _       # Delimiter to be used between the qualifier and the actual page number and size properties.
        size-parameter: size         # Page size parameter name.
        sort:
          sort-parameter: id         # Sort parameter name.
  main:
    web-application-type: servlet
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    password: 123456
    username: postgres
  jpa:
    database: POSTGRESQL
    show-sql: false
    open-in-view: true
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
        temp:
          use_jdbc_metadata_defaults: false