# ========================
#  Logger
# =======================
logging:
  level:
    root: INFO
    springboot.test: DEBUG
    com.zaxxer.hikari: WARN
    org.hibernate: WARN
    org.flywaydb.core: WARN
    org.apache.catalina: WARN
    org.springframework.boot.devtools: WARN
  pattern:
    console: "%d{dd HH:mm:ss.SSS} %-5level [%8.15thread] %-120.120(%logger{100}.%method %line) %n%m%n"

server:
  port: 8080
  version: 1.0.0
  name: spring-demo
spring:
  main:
    web-application-type: servlet
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: 3600
  # ========================
  #  Query Pageable
  # =======================
  data:
    web:
      pageable:
        default-page-size: 10        # Default page size. (default: 20)
        max-page-size: 2000          # Maximum page size to be accepted. (default: 2000)
        one-indexed-parameters: true # Whether to expose and assume 1-based page number indexes.
        page-parameter: page         # Page index parameter name.
        prefix:                      # General prefix to be prepended to the page number and page size parameters.
        qualifier-delimiter: _       # Delimiter to be used between the qualifier and the actual page number and size properties.
        size-parameter: size         # Page size parameter name.
      sort:
        sort-parameter: sort         # sort parameter name.
  # ========================
  #  Database
  # =======================
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydb?useUnicode=true&characterEncoding=utf-8
    username: postgres
  jpa:
    database: POSTGRESQL
    show-sql: false
    open-in-view: true
    properties:
      hibernate:
        default_schema: testt
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  # =========================
  #  Flyway
  # ==========================
  flyway:
    baseline-version: 1.0
    enabled: false


